// <auto-generated />
using System;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using Taskflow.Infrastructure.Context;

#nullable disable

namespace Taskflow.Infrastructure.Context.Migrations
{
    [DbContext(typeof(TaskflowDbContext))]
    partial class TaskflowDbContextModelSnapshot : ModelSnapshot
    {
        protected override void BuildModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "8.0.27")
                .HasAnnotation("Relational:MaxIdentifierLength", 64);

            MySqlModelBuilderExtensions.AutoIncrementColumns(modelBuilder);

            modelBuilder.Entity("Taskflow.Domain.Entities.CommentEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Content")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("TaskId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("CreatedBy");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("TaskId");

                    b.ToTable("Comments");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.DashboardEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Dashboards");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.FileEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("ContentType")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("FileName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Files");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.LinkEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Key")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<float>("LifeTime")
                        .HasColumnType("float");

                    b.Property<Guid?>("ProjectAccessId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectAccessId");

                    b.HasIndex("ProjectId");

                    b.ToTable("Links");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.LinkUserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<Guid>("LinkId")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("LinkId");

                    b.HasIndex("UserId");

                    b.ToTable("LinkUsers");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.MarkdownEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<string>("Color")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectId");

                    b.ToTable("Markdowns");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.ProjectAccessEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<bool>("CanCreateTasks")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanManageUsers")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanRemoveTasks")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("CanUpdateTasks")
                        .HasColumnType("tinyint(1)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<bool>("IsOwner")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<Guid?>("ProjectAccessEntityId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectAccessEntityId");

                    b.HasIndex("ProjectId");

                    b.ToTable("ProjectAccesses");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.ProjectEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("Projects");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.ProjectMemberEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("ProjectAccessId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("ProjectId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("ProjectAccessId");

                    b.HasIndex("ProjectId");

                    b.HasIndex("UserId");

                    b.ToTable("ProjectMembers");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.TaskEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("DashboardId")
                        .HasColumnType("char(36)");

                    b.Property<string>("Description")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("EndDate")
                        .HasColumnType("datetime(6)");

                    b.Property<int>("Index")
                        .HasColumnType("int");

                    b.Property<bool>("IsDeleted")
                        .HasColumnType("tinyint(1)");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("RowVersion")
                        .IsConcurrencyToken()
                        .ValueGeneratedOnAddOrUpdate()
                        .HasColumnType("timestamp(6)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime(6)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("DashboardId");

                    b.ToTable("Tasks");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.TaskMarkDownEntity", b =>
                {
                    b.Property<Guid>("TaskId")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("MarkDownId")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("Id")
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.HasKey("TaskId", "MarkDownId");

                    b.HasIndex("MarkDownId");

                    b.ToTable("TaskMarkDowns");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.UserEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid?>("FileId")
                        .HasColumnType("char(36)");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserPasswordId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.HasIndex("FileId")
                        .IsUnique();

                    b.HasIndex("UserPasswordId")
                        .IsUnique();

                    b.ToTable("Users");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.UserPasswordEntity", b =>
                {
                    b.Property<Guid>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("char(36)");

                    b.Property<DateTime>("CreatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid?>("CreatedBy")
                        .HasColumnType("char(36)");

                    b.Property<string>("Login")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Password")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<string>("Salt")
                        .IsRequired()
                        .HasColumnType("longtext");

                    b.Property<DateTime>("UpdatedAt")
                        .HasColumnType("datetime(6)");

                    b.Property<Guid>("UpdatedBy")
                        .HasColumnType("char(36)");

                    b.Property<Guid>("UserId")
                        .HasColumnType("char(36)");

                    b.HasKey("Id");

                    b.ToTable("UserPasswords");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.CommentEntity", b =>
                {
                    b.HasOne("Taskflow.Domain.Entities.UserEntity", "User")
                        .WithMany("Comments")
                        .HasForeignKey("CreatedBy")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Taskflow.Domain.Entities.FileEntity", "File")
                        .WithOne("Comment")
                        .HasForeignKey("Taskflow.Domain.Entities.CommentEntity", "FileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Taskflow.Domain.Entities.TaskEntity", "Task")
                        .WithMany("Comments")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("Task");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.DashboardEntity", b =>
                {
                    b.HasOne("Taskflow.Domain.Entities.ProjectEntity", "Project")
                        .WithMany("Dasboards")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.LinkEntity", b =>
                {
                    b.HasOne("Taskflow.Domain.Entities.ProjectAccessEntity", "ProjectAccess")
                        .WithMany("Links")
                        .HasForeignKey("ProjectAccessId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Taskflow.Domain.Entities.ProjectEntity", "Poject")
                        .WithMany("Links")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Poject");

                    b.Navigation("ProjectAccess");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.LinkUserEntity", b =>
                {
                    b.HasOne("Taskflow.Domain.Entities.LinkEntity", "Link")
                        .WithMany("LinkUsers")
                        .HasForeignKey("LinkId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taskflow.Domain.Entities.UserEntity", "User")
                        .WithMany("LinkUsers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Link");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.MarkdownEntity", b =>
                {
                    b.HasOne("Taskflow.Domain.Entities.ProjectEntity", "Project")
                        .WithMany("Markdowns")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.ProjectAccessEntity", b =>
                {
                    b.HasOne("Taskflow.Domain.Entities.ProjectAccessEntity", null)
                        .WithMany("ProjectAccesses")
                        .HasForeignKey("ProjectAccessEntityId");

                    b.HasOne("Taskflow.Domain.Entities.ProjectEntity", "Project")
                        .WithMany("ProjectAccesses")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Project");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.ProjectMemberEntity", b =>
                {
                    b.HasOne("Taskflow.Domain.Entities.ProjectAccessEntity", "ProjectAccess")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectAccessId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.HasOne("Taskflow.Domain.Entities.ProjectEntity", "Project")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("ProjectId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taskflow.Domain.Entities.UserEntity", "User")
                        .WithMany("ProjectMembers")
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.SetNull);

                    b.Navigation("Project");

                    b.Navigation("ProjectAccess");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.TaskEntity", b =>
                {
                    b.HasOne("Taskflow.Domain.Entities.DashboardEntity", "Dashboard")
                        .WithMany("Tasks")
                        .HasForeignKey("DashboardId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Dashboard");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.TaskMarkDownEntity", b =>
                {
                    b.HasOne("Taskflow.Domain.Entities.MarkdownEntity", "Markdown")
                        .WithMany("Tasks")
                        .HasForeignKey("MarkDownId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Taskflow.Domain.Entities.TaskEntity", "Task")
                        .WithMany("Markdowns")
                        .HasForeignKey("TaskId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("Markdown");

                    b.Navigation("Task");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.UserEntity", b =>
                {
                    b.HasOne("Taskflow.Domain.Entities.FileEntity", "File")
                        .WithOne("User")
                        .HasForeignKey("Taskflow.Domain.Entities.UserEntity", "FileId")
                        .OnDelete(DeleteBehavior.Cascade);

                    b.HasOne("Taskflow.Domain.Entities.UserPasswordEntity", "UserPassword")
                        .WithOne("User")
                        .HasForeignKey("Taskflow.Domain.Entities.UserEntity", "UserPasswordId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.Navigation("File");

                    b.Navigation("UserPassword");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.DashboardEntity", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.FileEntity", b =>
                {
                    b.Navigation("Comment");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.LinkEntity", b =>
                {
                    b.Navigation("LinkUsers");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.MarkdownEntity", b =>
                {
                    b.Navigation("Tasks");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.ProjectAccessEntity", b =>
                {
                    b.Navigation("Links");

                    b.Navigation("ProjectAccesses");

                    b.Navigation("ProjectMembers");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.ProjectEntity", b =>
                {
                    b.Navigation("Dasboards");

                    b.Navigation("Links");

                    b.Navigation("Markdowns");

                    b.Navigation("ProjectAccesses");

                    b.Navigation("ProjectMembers");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.TaskEntity", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("Markdowns");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.UserEntity", b =>
                {
                    b.Navigation("Comments");

                    b.Navigation("LinkUsers");

                    b.Navigation("ProjectMembers");
                });

            modelBuilder.Entity("Taskflow.Domain.Entities.UserPasswordEntity", b =>
                {
                    b.Navigation("User")
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
