<Project Sdk="Microsoft.NET.Sdk.Web">

    <PropertyGroup>
        <TargetFramework>net8.0</TargetFramework>
        <Nullable>enable</Nullable>
        <ImplicitUsings>enable</ImplicitUsings>
        <OutputType>Library</OutputType>
    </PropertyGroup>

    <ItemGroup>
      <None Remove="Properties\launchSettings.json" />
    </ItemGroup>

    <ItemGroup>
      <PackageReference Include="AutoMapper" Version="16.1.1" />
      <PackageReference Include="BCrypt" Version="1.0.0" />
      <PackageReference Include="Microsoft.AspNetCore.Authentication.JwtBearer" Version="8.0.27" />
    </ItemGroup>

    <ItemGroup>
      <ProjectReference Include="..\Taskflow.Domain\Taskflow.Domain.csproj" />
    </ItemGroup>

    <ItemGroup>
      <Reference Include="DevOne.Security.Cryptography.BCrypt">
        <HintPath>..\..\..\..\..\..\..\.nuget\packages\bcrypt\1.0.0\lib\DevOne.Security.Cryptography.BCrypt.dll</HintPath>
      </Reference>
      <Reference Include="Microsoft.EntityFrameworkCore">
        <HintPath>..\..\..\..\..\..\..\.nuget\packages\microsoft.entityframeworkcore\8.0.27\lib\net8.0\Microsoft.EntityFrameworkCore.dll</HintPath>
      </Reference>
    </ItemGroup>

</Project>
